name: herro's deployment
on:
  push:
    branches:
      - main
    paths:
      - 'dataCollection/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.RAKSHIL_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.RAKSHIL_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 554192822376.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: 554192822376.dkr.ecr.ap-southeast-2.amazonaws.com
          ECR_REPOSITORY: datacollection1
          IMAGE_TAG: latest
        run: |
          docker build -f dataCollection/Dockerfile --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./dataCollection
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update ECS task definition
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./dataCollection/col_Task_definition.json
          service: data-col-service
          cluster: datacol1
          container-name: data
          image: ${{ steps.build-image.outputs.image }}