name: Deploy to ECS

on:
  push:
    branches:
      - main
    paths:
      - 'retrievalService/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ANUJAN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ANUJAN_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 339712883212.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: 339712883212.dkr.ecr.ap-southeast-2.amazonaws.com
          ECR_REPOSITORY: seng3011-omega-microservice-repo
          IMAGE_TAG: latest
        run: |
          docker build -f retrievalService/Dockerfile --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./retrievalService
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update ECS task definition
        id: deploy-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/retrieval_task_definition.json
          service: retrieval-service
          cluster: seng3011-omega-retrieval-cluster
          container-name: retrieval-service-container
          image: ${{ steps.build-image.outputs.image }}
      